version: "3.8"
services:
  reorder-app:
    build: .
    ports:
      - "8000:8000"   # FastAPI
      - "8501:8501"   # Streamlit
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

